### PR TITLE
Facedancer 2.3

### PR DESCRIPTION
**Pull request by bkerler**
This pull request adds several fixes for Facedancer 2.2, an automatic device detection for device emulation (just copy script to devices path and make sure the device class name has the structure "USB[Devicename]Device" and the next line includes the description as variable "name") and new features known from umap2, such as vid/pid scanner and fuzzer.

It also does add several new devices, all of them tested.

Hope you do like my contribution :) See you at Troopers.

### CODE REVIEW

**Comment by dominicgs** [comment]
I've not reviewed the whole PR, but I have a couple of concerns that need to be resolved first:
 * Licensing - A reasonable amount of the code in this appears to come from umap2, which is AGPLv3 licensed.  Do you have permission from the umap2 authors to re-license this as BSD for inclusion in the facedancer project?
 * This was forked from FaceDancer in March 2018, and is not currently mergeable because it conflicts with 12 files in the repo.
 * FaceDancer is a USB exploration and development framework, is it appropriate to include the entire kitty tree within it?  I think that would make more sense as an external dependency or submodule (if it needs to be)
 * Is there a reason that we're bumping the version number of FaceDancer?

**Comment by bkerler** [comment]
Licensing - A reasonable amount of the code in this appears to come from umap2, which is AGPLv3 licensed. Do you have permission from the umap2 authors to re-license this as BSD for inclusion in the facedancer project?
-> Yes, good point. Actually I ported umap2 stuff to FaceDancer but there may be code parts I just copied from umap2. I didn't see it was licensed by AGPLv3.

This was forked from FaceDancer in March 2018, and is not currently mergeable because it conflicts with 12 files in the repo.
-> It was updated to reflect all updated up to the latest master branch.

FaceDancer is a USB exploration and development framework, is it appropriate to include the entire kitty tree within it? I think that would make more sense as an external dependency or submodule (if it needs to be)
- True. This is only due to fixes I added any will be moved to a submodule once the fixes are integrated.

Is there a reason that we're bumping the version number of FaceDancer?
- Only to differ from 2.2 due to the new feature set.

As I do not see any chance to move the now AGPLv3 code to BSD-Only license,
I will close this commit. Thanks for letting me know.

**Comment by ktemkin** [comment]
Hi, @bkerler -- I definitely appreciate the work that's going into this and I think with a little bit of work we can definitely figure out how to provide some of the functionality from this PR across other tools.

I'd be happy to talk over plans for this, if you're interested -- it'd be good to have a plan going forward, both to keep things in sync and to try and figure out a good plan for keeping what work we can from this PR. :)

**Comment by bkerler** [comment]
Yes, sounds like a good plan. I've contacted NCC Group for relicensing of Umap2, but as the original author no longer works for them (he would agree with relicensing as BSD but it's the NCC Group repo and thus their decision) and the head of research also left, there is little hope. So it looks like umap2 is no longer maintained.

**Comment by dominicgs** [comment]
To fix the licensing issues, I would recommend:
 * Moving kitty to a separate repo (under your github handle) while you see if your changes can be upstreamed.  We can update the documentation so that uses who want it can clone it and build against it.

 * If umap2 can't be relicensed, how about using the same model that they use?  Maintain it in a separate repo and wrap the FaceDance 2.3 module / tools.

**Comment by ktemkin** [comment]
If umap2 can't be relicensed, how about using the same model that they use? Maintain it in a separate repo and wrap the FaceDance 2.3 module / tools.

I think @dominicgs has the right approach, here. FaceDancer is, at its core, a library as much as it is a tool-- it'd designed to be able to empower downstream tools. I don't see any reason why an updated umap shouldn't live in its own repository, and then consume FaceDancer to provide the backend.

    Moving kitty to a separate repo (under your github handle) while you see if your changes can be upstreamed

I'd definitely prefer not to have an inline version of Kitty (or a personal fork) in the maintenance surface area of FaceDancer. If there's a way we can use upstream kitty, I'd think this sounds like the way to go.

Also, a couple of things I'd generally like as we figure out how to move forward with this:

    - Where possible, I'd appreciate it if you could be careful about providing attribution (and clearly indicating authorship). I definitely don't want to (even accidentally) have someone not be credited for their work.
    - For future work, it'd be nice to collaborate more on plans for work like this-- that'll help us to synchronize on features and to avoid duplication of work.

**Pull request closed without merging**
